### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by koenyskout** [VincentCheval/language-proverif#3]
From the ProVerif manual (v1.97pl1, page 15), this is the list of reserved words: 
**_among_**, **_channel_**, **_choice_**, **_clauses_**, const, **_def_**, **_diff_**, **_elimtrue_**, else, equation, **_equivalence_**, event,
**_expand_**, **_fail_**, forall, free, fun, get, if, in, inj-event, insert, let, letfun, new, **_noninterf_**, **_not_**,
**_nounif_**, **_or_**, otherwise, out, **_param_**, phase, pred, **_proba_**, process, **_proof_**, **_putbegin_**, query, reduc,
set, suchthat, **_sync_**, table, then, type, **_weaksecret_**, **_yield_**

The ones in bold are not yet present in the current language description.

**Comment by VincentCheval** [comment]
I added all of them. Thanks ! 5c8f573
